seeleteam/scan

- README.md
- src/components/account/detail.vue
- src/components/account/index.vue
- src/components/node/detail.vue
- src/components/node/index.vue
- src/components/stat-char/charts/chart-account.vue
- src/components/stat-char/charts/chart-blockavgtime.vue
- src/components/stat-char/charts/chart-blockcount.vue
- src/components/stat-char/charts/chart-difficulty.vue
- src/components/stat-char/charts/chart-hashrate.vue
- src/components/stat-char/charts/chart-miner.vue
- src/components/stat-char/charts/chart-nodes.vue
- src/components/stat-char/charts/chart-txhistory.vue
- src/components/stat-char/nodes.vue
- src/components/transaction/index.vue
- src/locale/en.js
- src/locale/zh.js
- src/store/modules/chart.js
- src/store/modules/pendingtxs.js
- src/store/modules/search.js
- src/store/modules/transaction.js
- src/untils/config.js
- src/untils/format.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/7)
> fix bug & update README

- src/assets/css/detail.less
- src/assets/css/list.less
- src/components/account/detail.vue
- src/components/contract/detail.vue
- src/components/nav.vue
- src/components/transaction/detail.vue
- src/components/transaction/index.vue
- src/locale/en.js
- src/locale/zh.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/9)
> detail tab

- src/components/footer.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/18)
> update weibo link at the footer

- src/components/menu.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/23)
> Change default lang settings from zh_cn to us_en

- src/components/header.vue
- src/components/menu.vue
- src/components/nav.vue
- src/main.js
1. input width
2. NAV drop-down menu background color spillover
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/24)
> modify bug

- src/components/menu.vue
- src/components/nav.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/26)
> nav api click add underline

- src/assets/css/list.less
- src/components/account/detail.vue
- src/components/account/tx-list.vue
- src/components/contract/detail.vue
- src/components/contract/tx-list.vue
- src/components/pendingtxs/detail.vue
- src/components/pendingtxs/index.vue
- src/components/transaction/detail.vue
- src/components/transaction/index.vue
- src/main.js
- src/untils/format.js
Connect the jump is ok
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/27)
> Connect the jump

- src/components/nav.vue
- src/components/stat-char/charts/chart-account.vue
- src/components/stat-char/charts/chart-blockavgtime.vue
- src/components/stat-char/charts/chart-blockcount.vue
- src/components/stat-char/charts/chart-difficulty.vue
- src/components/stat-char/charts/chart-hashrate.vue
- src/components/stat-char/charts/chart-miner.vue
- src/components/stat-char/charts/chart-nodes.vue
- src/components/stat-char/charts/chart-txhistory.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/28)
> The download icon tooltip of the modified statistics is truncated

- src/components/stat-char/charts/chart-account.vue
- src/components/stat-char/charts/chart-blockavgtime.vue
- src/components/stat-char/charts/chart-blockcount.vue
- src/components/stat-char/charts/chart-difficulty.vue
- src/components/stat-char/charts/chart-hashrate.vue
- src/components/stat-char/charts/chart-miner-phone.vue
- src/components/stat-char/charts/chart-miner.vue
- src/components/stat-char/charts/chart-txhistory.vue
- src/components/stat-char/miner.vue
- src/main.js
- src/store/modules/chart.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/29)
> fix scan chart bug

- src/components/stat-char/account.vue
- src/locale/en.js
- src/locale/zh.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/30)
> fix chart description

- config/dev.env.js
- config/index.js
- config/prod.env.js
- config/test.env.js
- package-lock.json
- package.json
- src/components/menu.vue
- src/components/nav.vue
- src/components/node/nodemap.vue
- src/components/stat-char/charts/chart-account.vue
- src/components/stat-char/charts/chart-blockavgtime.vue
- src/components/stat-char/charts/chart-blockcount.vue
- src/components/stat-char/charts/chart-difficulty.vue
- src/components/stat-char/charts/chart-hashrate.vue
- src/components/stat-char/charts/chart-miner.vue
- src/components/stat-char/charts/chart-nodes.vue
- src/components/stat-char/charts/chart-txhistory.vue
- src/components/stat-char/index.vue
- src/locale/en.js
- src/locale/zh.js
- src/main.js
- src/untils/config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/33)
> Conflict resolution

- src/components/stat-char/charts/chart-nodes.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/34)
> merge supplement

- config/dev.env.js
- config/index.js
- config/prod.env.js
- config/test.env.js
- src/assets/css/detail.less
- src/components/contract/detail.vue
- src/components/contract/index.vue
- src/untils/config.js
style is ok
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/35)
> contract-detail style

- src/components/account/detail.vue
- src/components/account/tx-list.vue
- src/components/contract/detail.vue
- src/components/contract/tx-list.vue
- src/components/node/index.vue
- src/components/pendingtxs/detail.vue
- src/components/pendingtxs/index.vue
- src/components/transaction/detail.vue
- src/components/transaction/index.vue
- src/untils/format.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/36)
> identification

- src/components/block/index.vue
- src/components/nav.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/39)
> 1. Modify the nav node point

- src/components/stat-char/charts/chart-miner-phone.vue
- src/components/stat-char/charts/chart-miner.vue
- src/untils/format.js
1. the miner's reward information From is the default address and should display Miner Reward.
2. [scan] statistical graph data view color disagreement
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/43)
> bug modify

- src/components/header.vue
- src/components/home/header.vue
- src/components/search-input.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/44)
> remove locale zh 

- src/locale/en.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/45)
> Explore -> Explorer

- src/components/search-input.vue
- src/components/transaction/detail.vue
- src/store/modules/search.js
2. the [scan] account shows that the transaction To is contract creation, but the transaction shows that To is empty, and the two should be unified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/46)
> 1. removal of space

- src/store/modules/search.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/47)
> Input space

- src/assets/css/detail.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/48)
> modify style

- src/components/node/index.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/51)
> Shield node -> country client

- config/dev.env.js
- config/prod.env.js
- config/test.env.js
- index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/52)
> 1. add data statistics  2. the way to change data requests is ip：port

- src/untils/config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/54)
> the way to change data requests is ip：port

- build/webpack.dev.conf.js
- build/webpack.prod.conf.js
- index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/55)
> add favicon.ico

- build/webpack.dev.conf.js
- build/webpack.prod.conf.js
- index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/57)
> favicon.ico

- src/components/nav.vue
- src/untils/format.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/58)
> Accounts  Contracts modified to one billion percentage

- src/untils/format.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/59)
> The percentage added is zero

- src/components/nav.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/61)
> repair nav

- src/components/transaction/detail.vue
- src/untils/request.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/62)
> repair style

- src/components/block/detail.vue
- src/components/node/detail.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/63)
> interface beautification

- src/assets/css/detail.less
- src/components/block/index.vue
- src/components/contract/detail.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/64)
> repair css

- src/components/account/detail.vue
- src/locale/en.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/65)
> Localized repair

- src/components/block/detail.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/68)
> block detail page remove loading effect

- src/components/block/detail.vue
- src/main.js
- src/untils/http.js
- src/untils/request.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/69)
> adjustment loading

- src/components/block/detail.vue
- src/components/node/index.vue
- src/router/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/70)
> 1. node add index   2. nav repair style

- src/components/contract/detail.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/71)
> Modify contract page

- src/components/node/index.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/72)
> Modify Node page

- src/untils/http.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/74)
> add interceptor default time

- src/components/block/index.vue
- src/locale/en.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/75)
> Blocks add reward fee

- src/components/pendingtxs/index.vue
- src/locale/en.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/76)
> Pending Txs add nonce fee

- src/components/transaction/index.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/seeleteam/scan/78)
> transaction add nonce fee
